import Head from 'next/head'
import Contact from '../components/Contact';
import Form from '../components/Form';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coping UK | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Contact
        heading="Let's Create"
        subhead="Stories for a Brighter Future"
        p="We'd love to hear from you!"
        email='info@copinguk.org'
        insta='@copinguk'
      />

      <Form heading='Get Early Ticket Access' message='We expect Coping Festival to sell out, so join our community for early access to secure your ticket!' formLabel='Email address' button='Sign up' />

    </div>
  );
}