import Head from 'next/head';
import Hero from '../components/Hero';

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Coping UK | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div> 
      <Hero heading='Connect With Our Community' message='Website Under Construction!' button='Saturday 27th August Event' message2='@COPINGUK'/>     
      </div>
    
    </div>
    
  );
}