
import Image from 'next/image'
import Hero from '../components/Hero'

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Coping UK | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </div>
  );
}