import Head from 'next/head'
import TestComponent from '../components/TestComponent';
import Image from 'next/image';

import Festival from '../components/Festival';
import Form from '../components/Form';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coping UK | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <TestComponent img={{
        src: '/coping-festival-girl-paints.png',
        alt: 'photo of child painting at coping festival'
      }} logo={<Image
        src='/Coping-festival-logo-white-2024.svg'
        alt='coping festival skateboarder kickflipping stairset at graystone action sports'
        width='250'
        height='120'
        className='object-conatin'
      />} title="Sat 22nd June" subtitle="Graystone Action Sports" body={(
        <>
          <p className='py-1 font-extralight text-lg text-white leading-6'>Feel the good vibes we create when we come together for something bigger than ourselves! This year we develop our long standing partnership with Graystone Action Sports to bring you another edition of Coping Festival. Amongst family friendly activities that promote wellbeing through creativity, our charity fundraiser will also feature the legendary Battle of the Stone. The yearly competition offering a whopping £6000 prize pot for individuals & teams with prize matching donations to The Ben Raemers Foundation will happen later in the day as the energy of the event rises. As always Coping Festival will be a not for profit event & all festival entry fees will go to The Ben Raemers Foundation.</p>
        </>
      )} ctaLink="/festival" ctaText="Get Your Tickets Here" flipImage/>

<TestComponent img={{
        src: '/Battle of the stone team slamma graphic 2024.svg',
        alt: 'coping festival battle of the stone team graphic 2000 pounds prize'
      }} logo={<Image
        src='/Battle of the stone graphic 2024.svg'
        alt='Battle of the stone graphic 2024'
        width='1000'
        height='1000'
        className='object-conatin'
      />} title="" subtitle="" body={(
        <>
          <p className='py-1 font-light text-md text-white leading-6'>Sign up for Battle of the Stone.</p>
        </>
      )} ctaLink="/festival" ctaText="Battle of the Stone Sign up" />
                  
      <Festival
      heading="Graystone Action Sports - Saturday 22nd June"
      subhead="Skating | Creating | Wellbeing" 
      h31="Fundraising for The Ben Raemers Foundation on the weekend of Go Skateboarding Day & Summer Solstice"
      p1="Coping Festival is our community and we’d love you to join us. We collaborate to raise money for charities by organising events that tell an ongoing story of togetherness. We encourage creative expression, action sports and wellbeing. "
      p2="Coping Festival 2024 will bring more individuals together to feel part of a caring community, raise more money for incredible causes that affect us all and tell the story of groups, businesses and brands who care about our collective mental health."
      p3="Family crafts, beginner lessons and fun competitions will develop throughout the day into live music and hardcore skating with Battle of the Stone offering up a whopping £5000 prize pot thanks to Oakley."
      p4="Click below & register to get access to early discount tickets."
      
      button='Join Our Community'/>

      

      <Form heading='Get Early Ticket Access' message='Register for early bird tickets to Coping Festival 2024 and join our community.' formLabel='Email address' button='Sign up'/>
      
    </div>
  );
}
