import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Strategy from '../components/Strategy';

import Festival from '../components/Festival';
import Form from '../components/Form';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coping UK | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero 
      heading="Stories For a Brighter Future" 
      message="We’re here to build communities & represent you in your best light." 
      button="Coping Festival" 
      button2="Coping Strategy"
      festival="Join our community"
      strategy="Build your community"
      />
                  
      <Festival
      heading="Skating | Creating | Wellbeing"
      subhead="Graystone Action Sports" 
      h31="Saturday 29th June"
      p1="Coping Festival is our community and we’d love you to join us. We collaborate to raise money for charities by organising events that tell an ongoing story of togetherness. We encourage creative expression, action sports and wellbeing. "
      p2="Coping Festival 2024 will bring more individuals together to feel part of a caring community, raise more money for incredible causes that affect us all and tell the story of groups, businesses and brands who care about our collective mental health."
      p3="Family crafts, beginner lessons and fun competitions will develop throughout the day into live music and hardcore skating with Battle of the Stone offering up a whopping £5000 prize pot thanks to Oakley."
      p4="Click below & register to get access to early discount tickets."
      
      button='Join Our Community'/>

      <Strategy
      heading='Logos | Brand ID | Websites' 
      subhead='Strategic Communication Design' 
      h31='Representing you in your best light' 
      p1="Our network of creative, strategic & technically skilled professionals provide a service to help build your community. We advise, design and build honest storytelling tools to inspire and influence your community."
      p2="Whatever your budget, we'll try our best to help you. From assembling a team to strategies, brand, design and build complex websites and apps to creating a simple logo or poster."
      p3="Our specialist area is storytelling that builds community and our ideal customers are honest, kind people looking to influence and uplift those around them, not tread on them to get to the top."
      p4="We design and build things that represent you in your best light. Courageous, honest and positive, your story is just getting started, let's collaborate to tell it in the most influential, inspirational way possible and build your community of loyal followers."
      
      button='Build Your Community'/>

      <Form heading='Get Early Ticket Access' message='Register for early bird tickets to Coping Festival 2024 and join our community.' formLabel='Email address' button='Sign up'/>
      
    </div>
  );
}
