import Head from 'next/head'
import Success from '../components/Success'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coping UK | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Success heading='Thanks for joining us' message='An ongoing movement for our collective mental health.' button='Home'/>
      
    </div>
  );
}