import Head from 'next/head'
import Image from 'next/image'
import TestComponent from '../components/TestComponent';

import Festival from '../components/Festival';
import Form from '../components/Form';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Coping UK | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <TestComponent img={{
        src: '/human kind illustration coping strategy.svg',
        alt: 'coping festival logo'
      }} title="" subtitle="Because your story needs telling" body={(
        <>
          <p className='py-1 font-extralight text-lg text-white leading-6'>We help build things that communicate your important message and develop a community around the great work you do. Our network allows us to assemble creative & technical dream teams capable of building almost anything to communicate your message. From logo packs & basic websites through to custom apps, long term partnerships & large scale marketing events - we’re here to build you a team that blows your customer’s mind!</p>
          
        </>
      )} ctaLink="/contact" ctaText="Book a free call" />

      <Form heading='Get Early Ticket Access' message='Register for early bird tickets to Coping Festival 2024 and join our community.' formLabel='Email address' button='Sign up'/>
      
    </div>
  );
}
